### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by MPParsley** [mdeverdelhan/ACR122U-reader-writer#3]
The app name is reader writer but from the help screen it is not clear how one can read in a card?

**Comment by mdeverdelhan** [comment]
Using the `--dump` argument. It is the only implemented way for now.

**Comment by Bubumuk** [comment]
@mdeverdelhan Can you detail what the args are?

**Comment by mdeverdelhan** [comment]
@Bubumuk The arguments are listed here: https://github.com/mdeverdelhan/ACR122U-reader-writer#usage
For the `--dump` option it is a list of keys needed to read all the sectors/blocks.
